# Enable C++ support
language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - COMPILER=g++-5.0
  - COMPILER=clang++-3.8

addons:
  apt:
    packages:
      - gcc-5
      - clang-3.8

# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
