# Enable C++ support
language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
apt:
  packages:
    - gcc-5
    - clang-3.8

sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: COMPILER=g++-5.0

    - os: linux
      dist: trusty
      sudo: required
      env: COMPILER=clang++-3.8

    - os: osx
      osx_image: xcode8.2
      env: COMPILER=clang++-3.8

# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
