# Enable C++ support
language: cpp

os:
  - linux
  - osx

sudo: required

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - gcc-5
      env: COMPILER=g++-5.0

    - compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
      env: COMPILER=clang++-3.8

# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
