# Enable C++ support
language: cpp

sudo: required

matrix:
  include:
    # Ubuntu 14.04 Trusty support
    - os: linux
      dist: trusty
    # OS X 10.12 support
    - os: osx
      osx_image: xcode8.2
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - gcc-5
      env: COMPILER=g++-5.0
  include:
    - compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
      env: COMPILER=clang++-3.8

# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
